#!/usr/bin/env python3
"""Apply a gsd-econ models-config YAML to the project's config files.

Reads a models-config YAML (schema documented in config/model-configs/README.md)
and writes:
  - .planning/config.json   — updates only the model_tiers field
  - opencode.json           — provider block, session model, permissions

Both writes are merge-and-preserve, not overwrite: existing user keys in
config.json or opencode.json are kept, only the model-related fields are
updated. Re-running this script with a different YAML is the supported
workflow for changing model choices.

Usage:
    python3 scripts/apply-models-config.py <models-config.yaml> <project-dir>

Exit codes:
    0  success
    1  YAML parse error or schema violation
    2  filesystem error
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "Error: PyYAML is required. Install with:\n"
        "  uv pip install pyyaml          # if using uv\n"
        "  pip3 install pyyaml --user     # otherwise",
        file=sys.stderr,
    )
    sys.exit(2)


# Provider-specific opencode.json provider block templates. These match the
# OpenCode schema as of opencode.ai/config.json (v0.18+, May 2026).
PROVIDER_TEMPLATES: dict[str, dict] = {
    "anthropic": {
        "options": {
            "apiKey": "{env:ANTHROPIC_API_KEY}",
        },
    },
    "openrouter": {
        "npm": "@ai-sdk/openai-compatible",
        "name": "OpenRouter",
        "options": {
            "baseURL": "https://openrouter.ai/api/v1",
            "apiKey": "{env:OPENROUTER_API_KEY}",
        },
    },
    "openai": {
        "options": {
            "apiKey": "{env:OPENAI_API_KEY}",
        },
    },
    "ollama": {
        "npm": "@ai-sdk/openai-compatible",
        "name": "Ollama (local)",
        "options": {
            "baseURL": "http://localhost:11434/v1",
            "apiKey": "ollama-no-key-needed",
        },
    },
}


def load_yaml(path: Path) -> dict:
    """Load and minimally validate the models-config YAML."""
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as e:
        print(f"Error parsing YAML at {path}: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(data, dict):
        print(f"Error: {path} is not a YAML mapping", file=sys.stderr)
        sys.exit(1)

    # Check required top-level keys.
    required = {"runtime", "provider", "tiers"}
    missing = required - set(data.keys())
    if missing:
        print(f"Error: missing required keys in {path}: {sorted(missing)}", file=sys.stderr)
        sys.exit(1)

    # Check tiers has light/standard/heavy.
    tiers = data.get("tiers", {})
    for t in ("light", "standard", "heavy"):
        if t not in tiers:
            print(f"Error: tiers.{t} missing in {path}", file=sys.stderr)
            sys.exit(1)
        if "/" not in tiers[t]:
            print(
                f"Error: tiers.{t} = '{tiers[t]}' must be provider-prefixed "
                "(e.g., 'anthropic/claude-opus-4-7')",
                file=sys.stderr,
            )
            sys.exit(1)

    return data


def merge_planning_config(project_dir: Path, config: dict) -> None:
    """Update .planning/config.json with model_tiers from the YAML.

    Preserves all other user fields. Creates the file from gsd-econ's example
    if it doesn't yet exist (the install.sh handles this on fresh installs;
    this script handles the case where someone calls it directly later).
    """
    planning_dir = project_dir / ".planning"
    planning_dir.mkdir(exist_ok=True)
    config_path = planning_dir / "config.json"

    if config_path.exists():
        try:
            existing = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"Error: {config_path} is not valid JSON: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        existing = {"version": 1}

    # Update model_tiers only, preserve everything else.
    tiers = dict(config["tiers"])
    tiers.setdefault(
        "_comment",
        "Generated by apply-models-config.py from the project's models-config "
        "YAML. Re-run with a different YAML to change model choices.",
    )
    existing["model_tiers"] = tiers

    config_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")
    print(f"  ✓ Updated {config_path}")


def write_opencode_json(project_dir: Path, config: dict) -> None:
    """Generate or update opencode.json with provider + session model + permissions."""
    opencode_path = project_dir / "opencode.json"

    if opencode_path.exists():
        try:
            existing = json.loads(opencode_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"Error: {opencode_path} is not valid JSON: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        existing = {"$schema": "https://opencode.ai/config.json"}

    provider_name = config["provider"]["name"]
    if provider_name not in PROVIDER_TEMPLATES:
        print(
            f"Warning: provider '{provider_name}' has no built-in template. "
            f"Writing a minimal provider block; you may need to add npm/name/options manually.",
            file=sys.stderr,
        )
        provider_block = {"options": {}}
    else:
        # Deep-copy template
        provider_block = json.loads(json.dumps(PROVIDER_TEMPLATES[provider_name]))

    # Apply YAML overrides to the provider block.
    yaml_provider = config["provider"]
    if "api_key_env" in yaml_provider:
        provider_block.setdefault("options", {})["apiKey"] = "{env:" + yaml_provider["api_key_env"] + "}"
    if "base_url" in yaml_provider:
        provider_block.setdefault("options", {})["baseURL"] = yaml_provider["base_url"]
    if "app_referer" in yaml_provider:
        provider_block.setdefault("options", {}).setdefault("headers", {})["HTTP-Referer"] = yaml_provider["app_referer"]
    if "app_title" in yaml_provider:
        provider_block.setdefault("options", {}).setdefault("headers", {})["X-Title"] = yaml_provider["app_title"]

    existing.setdefault("provider", {})[provider_name] = provider_block

    # Set session default model.
    if "session_default" in config:
        existing["model"] = config["session_default"]

    # Set permissions.
    if "permissions" in config:
        perms = config["permissions"]
        opencode_perms: dict = {}
        if "edit" in perms:
            opencode_perms["edit"] = perms["edit"]
        if "webfetch" in perms:
            opencode_perms["webfetch"] = perms["webfetch"]
        if "bash" in perms:
            opencode_perms["bash"] = perms["bash"]
        existing["permission"] = opencode_perms

    # Ensure AGENTS.md is in instructions (the framework's load-bearing file).
    instructions = existing.get("instructions", [])
    if isinstance(instructions, list) and "AGENTS.md" not in instructions:
        instructions.append("AGENTS.md")
        existing["instructions"] = instructions
    elif not instructions:
        existing["instructions"] = ["AGENTS.md"]

    opencode_path.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")
    print(f"  ✓ Updated {opencode_path}")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    yaml_path = Path(argv[1])
    project_dir = Path(argv[2])

    if not yaml_path.exists():
        print(f"Error: models-config not found at {yaml_path}", file=sys.stderr)
        return 1
    if not project_dir.exists():
        print(f"Error: project dir not found at {project_dir}", file=sys.stderr)
        return 2

    config = load_yaml(yaml_path)
    print(f"→ Applying {yaml_path} to {project_dir}")

    merge_planning_config(project_dir, config)

    # opencode.json only makes sense for opencode runtime.
    runtime = config.get("runtime", "")
    if runtime in ("opencode", "both"):
        write_opencode_json(project_dir, config)
    else:
        print(f"  (skipping opencode.json since runtime='{runtime}')")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
